[dev]
autoLaunch = false
command = "astro dev"

[build]
command = "astro build"

[[headers]]
for = "/*"
[headers.values]
Content-Type = "text/html"

[[headers]]
for = "/styles/*"
[headers.values]
Content-Type = "text/css"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "text/javascript"

[[headers]]
for = "/jwks.json"
[headers.values]
Content-Type = "text/json"

[[headers]]
for = "/favicon.ico"
[headers.values]
Content-Type = "image/vnd.microsoft.icon"

[[headers]]
for = "/favicon.svg"
[headers.values]
Content-Type = "image/svg+xml"

[[headers]]
for = "/touch-icon.svg"
[headers.values]
Content-Type = "image/svg+xml"

[[headers]]
for = "/images/blank.png"
[headers.values]
Content-Type = "image/png"
